### ISSUE TITLE
Fabric stops working in node for version 4.5.0+

### ISSUE THREAD

**Issue by jimjiang07** [fabricjs/fabric.js#7345]
I noticed a few node.js breaking changes have been introduced since 4.4.0. 

1. In Text class, there is a change for supporting LTR text (introduced in 4.5.0)https://github.com/fabricjs/fabric.js/blob/fd8a6dd334ee1f5b211127df6d3b6fe4b50ba511/src/shapes/text.class.js#L1026-L1028 

2. In Static Canvas Class, (introduced in 4.6.0)
https://github.com/fabricjs/fabric.js/blob/fd8a6dd334ee1f5b211127df6d3b6fe4b50ba511/src/static_canvas.class.js#L1774

## Version
4.5.0+

## Information about the environment
Nodejs

## Expected Behavior
Check `fabric.isLikelyNode` for features that are not supported in node-canvas yet. I can see the older code does check this. It's just the recent changes are not doing this.

## Actual Behavior
1. Getting error `setAttribute is not a function` when running in node
2. Getting error `TypeError: Cannot read property 'remove' of undefined` in node

**Comment by asturur** [comment]
oh weird i thought JSDOM would take care of that.
I will see if i can fix those bumping up JSDOM or adding conditional code.
The NODE JS test do pass anyway.
On what platform are you running?

**Comment by jimjiang07** [comment]
hi @asturur, any update on this issue? I recently tried to upgrade to 5.2.1 and I am still getting the same issues. I am running it on a docker container with node:14.17.0-slim as the base image.
