### ISSUE TITLE
[Bug]: animate method report an error when use it on strokeDashArray property

### ISSUE THREAD

**Issue by mikab** [fabricjs/fabric.js#8608]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/7k4zhj1L/1/

### Steps To Reproduce

1. Create a fabric.Line in a canvas
2. Use line.animate method do a strokeDashArray changing animation
3. An script error reported in console

### Expected Behavior

This code works fine in 4.6.0

### Actual Behavior

An script error reported in console  and onComplete method not be invoked.
![1674005893229](https://user-images.githubusercontent.com/7811209/213059964-fda02120-7448-42a9-92dd-cbced2b9ff3c.png)

### Error Message & Stack Trace

```bash
TypeError: endValue.slice is not a function
```
